
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: kininaru_development

test:
  <<: *default
  database: kininaru_test

production:
  <<: *default
  database: kininaru_production
  username: kininaru
  password: <%= ENV['KININARU_DATABASE_PASSWORD'] %>
